name: Build, Test, and Deploy to AWS App Runner

on:
  push:
    branches:
    - master

env:
  AWS_REGION: ap-northeast-1  # 請根據您的需求更改區域
  ECR_REPOSITORY: daddy  # 請替換為您的 ECR 倉庫名稱
  APP_RUNNER_SERVICE: reurl  # 請替換為您的 App Runner 服務名稱

jobs:
  build-test-deploy: 
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t ${{ secrets.ECR }}:$IMAGE_TAG .
        docker push ${{ secrets.ECR }}:$IMAGE_TAG

    - name: Run tests
      run: |
        # 在這裡添加您的測試命令
        # 例如：npm test 或 python -m pytest
        echo "Running tests..."
        # 添加輸入測試的命令，例如：
        # python test_input.py

    - name: Deploy to App Runner
      run: |
        aws apprunner update-service \
          --service-arn ${{ secrets.ARN }} \
          --source-configuration '{
            "ImageRepository": {
              "ImageIdentifier": "${{ secrets.ECR }}:${{ github.sha }}",
              "ImageRepositoryType": "ECR",
              "ImageConfiguration": {
                "Port": "80"
              }
            }
          }'