name: Build, Test, and Deploy to AWS App Runner

on:
  push:
    branches:
    - master

env:
  AWS_REGION: ap-northeast-1  # 請根據您的需求更改區域
  ECR_REPOSITORY: daddy  # 請替換為您的 ECR 倉庫名稱
  APP_RUNNER_SERVICE: reurl  # 請替換為您的 App Runner 服務名稱

jobs:
  build-test-deploy: 
    name: Build, Test, and Deploy
    runs-on: nginx:1.26.2-alpine

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR }}
      run: |
        docker build -t reurl .
        docker push ${{ secrets.ECR }}:latest

    - name: Run tests
      run: |
        # 在這裡添加您的測試命令
        # 例如：npm test 或 python -m pytest
        echo "Running tests..."
        # 添加輸入測試的命令，例如：
        # python test_input.py

    - name: Deploy to App Runner
      run: |
        aws apprunner create-service \
          --service-name reurl \
          --source-configuration '{
            "AuthenticationConfiguration": {
              "AccessRoleArn": ${{ secrets.ARN }}
            },
            "ImageRepository": {
              "ImageIdentifier": ${{ secrets.ECR }},
              "ImageRepositoryType": "ECR",
              "ImageConfiguration": {
                "Port": "80"
              }
            }
          }' \
          --instance-configuration '{
            "Cpu": "1 vCPU",
            "Memory": "2 GB"
          }'